//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haiku.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Haiku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing.
        /// </summary>
        internal static string DECOMPRESSING {
            get {
                return ResourceManager.GetString("DECOMPRESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Decompressing.
        /// </summary>
        internal static string DONE_DECOMPRESSING {
            get {
                return ResourceManager.GetString("DONE_DECOMPRESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device found...
        /// </summary>
        internal static string FOUND {
            get {
                return ResourceManager.GetString("FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catching data from server...
        /// </summary>
        internal static string GETTING_DATA_FROM_SERVER {
            get {
                return ResourceManager.GetString("GETTING_DATA_FROM_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IOException accured probably are the filesystem not recognized. We will run any way but you will need to check that your USB are atleast.
        /// </summary>
        internal static string IOEXEPTION_RUN_ANYWAY {
            get {
                return ResourceManager.GetString("IOEXEPTION_RUN_ANYWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have room on your drive to download and extract an image.
        /// </summary>
        internal static string NO_ROOM {
            get {
                return ResourceManager.GetString("NO_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device was found.
        /// </summary>
        internal static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a destination.
        /// </summary>
        internal static string NOT_SELECTED {
            get {
                return ResourceManager.GetString("NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to write a image to.
        /// </summary>
        internal static string QUESTION_WRITE_TO {
            get {
                return ResourceManager.GetString("QUESTION_WRITE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected file.
        /// </summary>
        internal static string SELECTED_FILE {
            get {
                return ResourceManager.GetString("SELECTED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Decompressing.
        /// </summary>
        internal static string START_DECOMPRESSING {
            get {
                return ResourceManager.GetString("START_DECOMPRESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Writing to USB.
        /// </summary>
        internal static string START_WRITE_TO_USB {
            get {
                return ResourceManager.GetString("START_WRITE_TO_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write image to USB.
        /// </summary>
        internal static string WRITE_TO_USB {
            get {
                return ResourceManager.GetString("WRITE_TO_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to USB.
        /// </summary>
        internal static string WRITING_TO_USB {
            get {
                return ResourceManager.GetString("WRITING_TO_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have Canceled.
        /// </summary>
        internal static string YOU_HAVE_CANCELED {
            get {
                return ResourceManager.GetString("YOU_HAVE_CANCELED", resourceCulture);
            }
        }
    }
}
